name: Enviar email
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: htoshioolyntho@gmail.com
        password: ${{secrets.PASSWORD}}
        subject: ME607_1s2023
        to: htoshioolyntho@hotmail.com
        from: htoshioolyntho@gmail.com
        body: | 
          Here follows the Shiny app with EDA and prediction!
          https://h172284.shinyapps.io/ME607_1S2023/
          
          The prediction dataset can be downloaded here
          https://github.com/Sputnik7829/ME607_1S2023/blob/main/max_temp_predictions.csv
          
          Henrique Toshio - 172284
          Bruno Martinez - 181980
          Pedro Dinamarco- 223397

