name: Executar scripts R diariamente
on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@master
    - name: Configurar R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'

    - name: Update Time Series
      run: Rscript series.R

    - name: Launch shinyapp
      run: Rscript updateapp.R
      
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: htoshioolyntho@gmail.com
        password: ${{secrets.PASSWORD}}
        subject: ME607_1s2023
        to: ctrucios@unicamp.br
        from: htoshioolyntho@gmail.com
        body: | 
          This mail is automaticly sent to you and is our final project for Time series course of UNICAMP, ME607, ministred by you in the first semester of 2023 
          Please verify if it didn't fall into your SPAM folder.
          Here follows the Shiny app with EDA and prediction!
          https://h172284.shinyapps.io/ME607_1S2023/
          
          The prediction dataset can be downloaded here
          https://github.com/Sputnik7829/ME607_1S2023/blob/main/max_temp_predictions.csv
          
          Henrique Toshio - 172284
          Bruno Martinez - 181980
          Pedro Dinamarco- 223397
