name: Executar scripts R e Python diariamente
on:
  workflow_dispatch:  # Executar todos os dias às 00:00 UTC

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@master
    - name: Configurar R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3'

    - name: Update Time Series
      run: Rscript series.R

    - name: Launch shinyapp
      run: Rscript updateapp.R
      
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
      # Server port, default 25:
        server_port: 587
      # Optional (recommended) mail server username:
        username: htoshioolyntho@gmail.com
      # Optional (recommended) mail server password:
        password: ${{secrets.PASSWORD}}
      # Required mail subject:
        subject: Github Actions job result
      # Required recipients' addresses:
        to: htoshioolyntho@hotmail.com
      # Required sender full name (address can be skipped):
        from: htoshioolyntho@gmail.com # <user@example.com>
      # Optional plain body:
        body: Build job of completed successfully!
           https://h172284.shinyapps.io/ME607_1S2023/
