name: Teste de email
on:
  workflow_dispatch: # Executar todos os dias às 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    # Required mail server address if not connection_url:
        server_address: smtp.sendgrid.net
      # Server port, default 25:
        server_port: 587
      # Optional (recommended) mail server username:
        username: ${{secrets.SENDGRID_USERNAME}}
      # Optional (recommended) mail server password:
        password: ${{secrets.SENDGRID_API_KEY}}
      # Required mail subject:
        subject: Github Actions job result
      # Required recipients' addresses:
        to: htoshioolyntho@hotmail.com
      # Required sender full name (address can be skipped):
        from: h172284@dac.unicamp.br # <user@example.com>
      # Optional plain body:
        body: Build job of completed successfully!

